### PR TITLE
Fix test and others

### PR DESCRIPTION
**Pull request by tamuratak**
Fix test and others.

### CODE REVIEW

**Comment by ineiti** [comment]
Thanks for fixing the tests - however, the `main.ts` should not be changed. Can you please undo these changes? In typescript, the return types are needed, unless js, where you can omit them.

**Comment by tamuratak** [comment]
You can omit  the return type in TypeScript.

See:
https://basarat.gitbook.io/typescript/type-system/type-inference#function-return-types

**Comment by ineiti** [comment]
OK - but wouldn't you prefer to have a working test that people can copy paste in their project? It took me 30' to find how to fill the `GlobalWorker`, and finally I found the answer in one of the issues. So this is something that I think would like to keep in the test as an example.

**Comment by tamuratak** [comment]
No. You can find examples [here](https://github.com/mozilla/pdf.js/tree/master/examples/components). And setting the imported value to `workSrc` is not a typical usage as you can see examples.

**Comment by tamuratak** [comment]
I think it is appropriate to put an example of TypeScript  under the `examples` directory, which would be another issue.

**Comment by ineiti** [comment]
Directly merged in https://github.com/mozilla/pdf.js/pull/12102 - only kept the original `test/ts-types/main.ts`

**Pull request closed without merging**
